# Generated by Django 5.0.4 on 2024-05-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                ("contact_details", models.TextField()),
                ("address", models.TextField()),
                (
                    "vendor_code",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("on_time_delivery_rate", models.FloatField(default=0)),
                ("quality_rating_avg", models.FloatField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("fulfillment_rate", models.FloatField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("po_number", models.CharField(editable=False, unique=True)),
                (
                    "order_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Datetime when the order was placed",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateTimeField(
                        help_text="Expected or actual delivery date of the order"
                    ),
                ),
                ("items", models.JSONField()),
                (
                    "quantity",
                    models.IntegerField(help_text="Total quantity of items in the PO"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (0, "Pending"),
                            (1, "Order Acknowledged"),
                            (2, "Completed"),
                            (3, "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current status of the PO",
                    ),
                ),
                (
                    "quality_rating",
                    models.FloatField(
                        blank=True,
                        help_text="Rating given to the vendor for this PO",
                        null=True,
                    ),
                ),
                (
                    "issue_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the PO was issued to the vendor",
                    ),
                ),
                (
                    "acknowledgement_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the vendor acknowledged the PO",
                        null=True,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_orders",
                        to="svc.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date of the performance record"
                    ),
                ),
                (
                    "on_time_delivery_rate",
                    models.FloatField(
                        help_text="Historical record of the on-time delivery rate"
                    ),
                ),
                (
                    "quality_rating_average",
                    models.FloatField(
                        help_text="Historical record of the quality rating average"
                    ),
                ),
                (
                    "average_response_time",
                    models.FloatField(
                        help_text="Historical record of the average response time"
                    ),
                ),
                (
                    "fulfillment_rate",
                    models.FloatField(
                        help_text="Historical record of the fulfilment rate"
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="svc.vendor"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
