# Generated by Django 5.0.4 on 2024-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
