# Generated by Django 5.0.4 on 2024-05-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("svc", "0003_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseorder",
            old_name="acknowledgement_date",
            new_name="acknowledgment_date",
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.CharField(
                choices=[(0, "Pending"), (1, "Completed"), (2, "Cancelled")],
                default=0,
                help_text="Current status of the PO",
            ),
        ),
    ]
